"""empty message

Revision ID: b9dc7c440935
Revises: 52691cfdba19
Create Date: 2020-04-05 19:18:44.762787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dc7c440935'
down_revision = '52691cfdba19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sell_items',
        sa.Column(
            'user_id',
            sa.Integer(),
            nullable=True))
    op.drop_constraint(
        'sell_items_user_fkey',
        'sell_items',
        type_='foreignkey')
    op.create_foreign_key(
        None,
        'sell_items',
        'users',
        ['user_id'],
        ['id'],
        ondelete='CASCADE')
    op.drop_column('sell_items', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'sell_items',
        sa.Column(
            'user',
            sa.INTEGER(),
            autoincrement=False,
            nullable=True))
    op.drop_constraint(None, 'sell_items', type_='foreignkey')
    op.create_foreign_key(
        'sell_items_user_fkey',
        'sell_items',
        'users',
        ['user'],
        ['id'],
        ondelete='CASCADE')
    op.drop_column('sell_items', 'user_id')
    # ### end Alembic commands ###
