"""empty message

Revision ID: f9fe02c70c89
Revises: 4d15a110e2e5
Create Date: 2020-04-02 19:01:44.649108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fe02c70c89'
down_revision = '4d15a110e2e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_seller', sa.Boolean(), nullable=True))
    op.drop_column('users', 'isSeller')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'isSeller',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True))
    op.drop_column('users', 'is_seller')
    # ### end Alembic commands ###
